<?php
/**
 * Implements hook_search_info()
 */
function bhle_search_search_info() {
    return array(
        'title' => 'simple',
        'path' => 'simple',
        'conditions_callback' => 'bhle_search_conditions',
    );
}

/**
 * Implements hook_FORMID_form_alter()
 */
function bhle_search_form_search_form_alter(&$form, $form_state) {
    $conditions = $_SESSION['bhle_search']['conditions'];
    
    $form['title'] = array(
        '#type' => 'checkbox',
        '#title' => t('Title'),
        '#default_value' => (isset($conditions['title'])) ? $conditions['title'] : 1,
    );
    
    $form['author'] = array(
        '#type' => 'checkbox',
        '#title' => t('Author'),
        '#default_value' => (isset($conditions['author'])) ? $conditions['author'] : 1,
    );
    
    $form['year'] = array(
        '#type' => 'checkbox',
        '#title' => t('Year'),
        '#default_value' => (isset($conditions['year'])) ? $conditions['year'] : 1,
    );
    
    $form['taxon_name'] = array(
        '#type' => 'checkbox',
        '#title' => t('Taxon Name'),
        '#default_value' => (isset($conditions['taxon_name'])) ? $conditions['taxon_name'] : 0,
    );
    
    $form['#validate'][] = 'bhle_search_simple_validate';
    
    return $form;
}

/**
 * Validate the search form (save checkbox settings in session)
 */
function bhle_search_simple_validate($form, &$form_state) {
    $conditions = array();
    
    $conditions['title'] = $form_state['values']['title'];
    $conditions['author'] = $form_state['values']['author'];
    $conditions['year'] = $form_state['values']['year'];
    $conditions['taxon_name'] = $form_state['values']['taxon_name'];
    
    // Official way to handle sessions is by directly writing into the super-globals
    // See: http://api.drupal.org/api/drupal/includes--session.inc
    $_SESSION['bhle_search']['conditions'] = $conditions;
}

/**
 * Callback which returns the search conditions (prepared in bhle_search_simple_validate)
 */
function bhle_search_conditions($keys) {
    return $_SESSION['bhle_search']['conditions'];
}

/**
 * Implements hook_search_execute()
 * Execute the search and return the results
 */
function bhle_search_search_execute($keys = NULL, $conditions = NULL) {
    $solr = apachesolr_get_solr( 1 );
    $query = '';
    $results = array();
    
    // Build the query for solr
    if( $conditions['title'] ) {
        $query .= ' ' . variable_get('bhle_search_title_field', 'name') . ':"' . $keys . '"';
    }
    if( $conditions['author'] ) {
        $query .= ' ' . variable_get('bhle_search_author_field', 'author') . ':"' . $keys . '"';
    }
    if( $conditions['year'] ) {
        $query .= ' ' . variable_get('bhle_search_year_field', 'last_modified') . ':"' . $keys . '"';
    }
    if( $conditions['taxon_name'] ) {
        $query .= ' ' . variable_get('bhle_search_taxon_name_field', 'keywords') . ':"' . $keys . '"';
    }
    
    // Query solr
    $responseObj = $solr->search($query);
    $response = $responseObj->response;
    // Check if we found something
    if( $response->numFound > 0 ) {
        $docs = $response->docs;
        
        foreach( $docs as $doc ) {
            $results[] = array(
                'link' => url('empty.html'),
                'title' => $doc->name,
            );
        }
    }
    
    return $results;
}

/**
 * Implements hook_menu().
 */
function bhle_search_menu() {
    $items = array();

    $items['admin/config/search/bhle'] = array(
        'title' => 'BHLE Search',
        'description' => 'Configuration for the BHLE search module',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bhle_search_config_simple_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['admin/config/search/bhle/simple'] = array(
        'title' => 'Simple',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bhle_search_config_simple_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_DEFAULT_LOCAL_TASK,
    );
    $items['admin/config/search/bhle/advanced'] = array(
        'title' => 'Advanced',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('bhle_search_config_advanced_form'),
        'access arguments' => array('access administration pages'),
        'type' => MENU_LOCAL_TASK,
    );


    return $items;
}

/**
 * Form function, called by drupal_get_form() 
 * in bhle_search_menu().
 */
function bhle_search_config_simple_form($form, &$form_state) {
    $form['bhle_search_title_field'] = array(
        '#type' => 'textfield',
        '#title' => t('Apache Solr index field for TITLE information.'),
        '#default_value' => variable_get('bhle_search_title_field', 'name'),
        '#size' => 15,
        '#description' => t('Set the Apache Solr index field which contains the title information.'),
        '#required' => TRUE,
    );

    $form['bhle_search_author_field'] = array(
        '#type' => 'textfield',
        '#title' => t('Apache Solr index field for AUTHOR information.'),
        '#default_value' =>  variable_get('bhle_search_author_field', 'author'),
        '#size' => 15,
        '#description' => t('Set the Apache Solr index field which contains the author information.'),
        '#required' => TRUE,
    );

    $form['bhle_search_year_field'] = array(
        '#type' => 'textfield',
        '#title' => t('Apache Solr index field for YEAR information.'),
        '#default_value' => variable_get('bhle_search_year_field', 'last_modified'),
        '#size' => 15,
        '#description' => t('Set the Apache Solr index field which contains the year information.'),
        '#required' => TRUE,
    );

    $form['bhle_search_taxon_name_field'] = array(
        '#type' => 'textfield',
        '#title' => t('Apache Solr index field for TAXON NAME information.'),
        '#default_value' => variable_get('bhle_search_taxon_name_field', 'keywords'),
        '#size' => 15,
        '#description' => t('Set the Apache Solr index field which contains the taxon name information.'),
        '#required' => TRUE,
    );

    return system_settings_form($form);
}

/**
 * Form function, called by drupal_get_form() 
 * in bhle_search_menu().
 */
function bhle_search_config_advanced_form($form, &$form_state) {
    return system_settings_form($form);
}
