
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0010.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0010.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0000.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0000.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0001.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0001.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0002.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0002.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0003.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0003.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0004.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0004.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0005.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0005.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0006.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0006.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0007.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0007.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0008.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0008.tif.txt"
wget -t 1 -O G:/dev/nhm/ingest/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0009.tif.tax "http://www.ubio.org/webservices/service.php?function=taxonFinder&includeLinks=0&url=http://bhl-celsus.nhm.ac.uk/uploads/testdata/spices_prepared/spice1/billederafnorden01lind_0009.tif.txt"


G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0010.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0010.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0000.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0000.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0001.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0001.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0002.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0002.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0003.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0003.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0004.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0004.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0005.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0005.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0006.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0006.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0007.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0007.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0008.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0008.tif
G:\dev\nhm\ingest\bin\imagemagick\convert.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\billederafnorden01lind_0009.jpg G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0009.tif


G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0010.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0010.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0000.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0000.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0001.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0001.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0002.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0002.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0003.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0003.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0004.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0004.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0005.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0005.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0006.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0006.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0007.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0007.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0008.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0008.tif -l eng 
G:\dev\nhm\ingest\bin\tesseract\tesseract.exe G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0009.tif G:\dev\nhm\ingest\uploads\testdata\spices_prepared\spice1\.aip\billederafnorden01lind_0009.tif -l eng 

