<?php
define('BHLE_TAGGING_ADD', 'Add to basket');
define('BHLE_TAGGING_REMOVE', 'Remove from basket');

define('BHLE_TAGGING_ADDED', '<a href="/bhle-basket"><strong>Added to your basket:</strong></a><br/><em>@item</em>');
define('BHLE_TAGGING_REMOVED', '<a href="/bhle-basket"><strong>Removed from your basket:</strong></a><br /><em>@item</em>');

/**
 * Implements hook_menu().
 */
function bhle_tagging_menu() {
  $items['bhle-basket'] = array(
    'title callback' => 'bhle_tagging_basket_title',
    'page callback' => 'bhle_tagging_basket_page',
    'access callback' => 'bhle_tagging_access',
    'type' => MENU_CALLBACK,
  );
  $items['bhle-tagging/%'] = array(
    'title callback' => 'bhle_tagging_operation_title',
    'title arguments' => array(1),
    'page callback' => 'bhle_tagging_operation_page',
    'page arguments' => array(1),
    'access callback' => 'bhle_tagging_access',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function bhle_tagging_permission() {
  $perms = array(
    'access bhle basket' => array(
      'title' => t('Access BHL Europe basket'),
    ),
  );
  return $perms;
}

/**
 * Access callback.
 */
function bhle_tagging_access() {
  global $user;
  return TRUE;
}

/**
 * Title callback.
 */
function bhle_tagging_basket_title($pid) {
  return t('Your basket');
}

/**
 * Title callback.
 */
function bhle_tagging_operation_title($pid) {
  drupal_load('module', 'bhle_item');
  $item = bhle_item_load($pid);
  return $item->mods_title[0] . t(' added/removed to your basket');
}

/*
 * Page callback for BHLE basket
 */
function bhle_tagging_basket_page() {
  if(is_array($_SESSION['bhle-tagging'])) {
    foreach ($_SESSION['bhle-tagging'] as $pid => $item) {
      $output .= l($item, 'bhle-view/' . $pid) . ' ( ' . $pid . ' )<br />';
    }
  } else {
    $output = t('No item in your basket.');
  }
  return $output;
}

/*
 * Page callback for non-ajax users
 */
function bhle_tagging_operation_page($pid) {
  return 'op done';
}

function bhle_tagging_operation_form($form, &$form_state, $pid = NULL, $title = NULL) {
  drupal_load('module', 'transliteration');
  module_load_all_includes('inc', 'transliteration');
  $safe_pid = str_replace(':', '-', transliteration_get($pid));
  $form['#prefix'] = '<div id="bhle-tag-' . $safe_pid . '">';
  $form['#suffix'] = '</div>';
  //$form['#action'] = 'bhle-tagging/' . $pid;
  $form['submit']['do'] = array(
    '#type' => 'submit',
    '#submit' => array('bhle_tagging_operation_submit'),
    '#ajax' => array(
      'method' => 'replaceWith',
      'event' => 'click',
      'wrapper' => 'bhle-tag-' . $safe_pid,
      'callback' => 'bhle_tagging_ajax_callback'
    ),
  );
  $form['pid'] = array(
    '#type' => 'hidden',
    '#value' => $pid
  );
  $form['title'] = array(
    '#type' => 'hidden',
    '#value' => $title
  );
  $form['bhle-tagging-action'] = array(
    '#type' => 'hidden',
  );

  if ($_SESSION['bhle-tagging'][$pid]) {
    $form['submit']['do']['#value'] = t(BHLE_TAGGING_REMOVE);
    $form['bhle-tagging-action']['#value'] = 'remove';
  } else {
    $form['submit']['do']['#value'] = t(BHLE_TAGGING_ADD);
    $form['bhle-tagging-action']['#value'] = 'add';
  }
  return $form;
}

function bhle_tagging_operation_submit($form, &$form_state) {
  if(arg(0) != 'system' && arg(1) != 'ajax') {
    $pid = $form_state['input']['pid'];
    $title = html_entity_decode($form_state['input']['title'], ENT_QUOTES, 'UTF-8');
    $action = $form_state['input']['bhle-tagging-action'];

    if ($_SESSION['bhle-tagging'][$pid] && $action == 'remove') {
      unset($_SESSION['bhle-tagging'][$pid]);
      drupal_set_message(t(BHLE_TAGGING_REMOVED, array('@item' => $title)));
    }
    if (!$_SESSION['bhle-tagging'][$pid] && $action == 'add') {
      $_SESSION['bhle-tagging'][$pid] = $title;
      drupal_set_message(t(BHLE_TAGGING_ADDED, array('@item' => $title)));
    }
  }
}

function bhle_tagging_ajax_callback($form, $form_state) {
  $pid = $form_state['input']['pid'];
  $title = html_entity_decode($form_state['input']['title'], ENT_QUOTES, 'UTF-8');
  $action = $form_state['input']['bhle-tagging-action'];
  
  if ($_SESSION['bhle-tagging'][$pid] && $action == 'remove') {
    unset($_SESSION['bhle-tagging'][$pid]);
    drupal_set_message(t(BHLE_TAGGING_REMOVED, array('@item' => $title)));
    $form['submit']['do']['#value'] = t(BHLE_TAGGING_ADD);
    $form['bhle-tagging-action']['#value'] = 'add';
    
  }
  if (!$_SESSION['bhle-tagging'][$pid] && $action == 'add') {
    $_SESSION['bhle-tagging'][$pid] = $title;
    drupal_set_message(t(BHLE_TAGGING_ADDED, array('@item' => $title)));
    $form['submit']['do']['#value'] = t(BHLE_TAGGING_REMOVE);
    $form['bhle-tagging-action']['#value'] = 'remove';
  }
  $basket = module_invoke('bhle_tagging', 'block_view', 'basket');
  
  $commands = array();
  $commands[] = ajax_command_insert(NULL, drupal_render($form));
  $commands[] = ajax_command_insert('#bhle-tagging-basket', $basket['content']);
  $commands[] = ajax_command_before('#results', theme('status_messages'));
  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Implements hook_block_info();
 */
function bhle_tagging_block_info() {
  $blocks['basket'] = array(
    'info' => t('BHLE basket'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view();
 */
function bhle_tagging_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'basket':
      $block['subject'] = t('Your basket');
      $block['content'] = '<div id="bhle-tagging-basket">';
      if (count($_SESSION['bhle-tagging'])) {
        $block['content'] .= l(t('@items items in basket', array('@items' => count($_SESSION['bhle-tagging']))), 'bhle-basket');
      } else {
        $block['content'] .= t('No items in basket');
      }
      $block['content'] .= '</div>';
      break;
  }
  return $block;
}
