<?php

/**
 * @file
 * Internationalization (i18n) module.
 *
 * Redirect to language path when we have a translation for the current language.
 */

/**
 * Implements hook_init()
 */
function i18n_redirect_init() {
  $path = $_GET['q'];
  $language = i18n_language();
  // Not for logged in users nor for home page
  if (!$path || drupal_is_front_page() || !empty($GLOBALS['user']->uid)) {
    return;
  }
  elseif ($translations = i18n_get_path_translations($path)) {
    if (isset($translations[$language->language]) && $translations[$language->language]['href'] != $path) {
      drupal_goto($translations[$language->language]['href'], array('language' => $language), 301);
    }
  }
}