<?php
// START TEST CODE
var_dump( col_lookup_common_name( "Eurasian Spoonbill" ) );
// END TEST CODE

function col_lookup_common_name( $common_name ) {
    $col_base = "http://www.catalogueoflife.org/col/webservice?response=full&format=php&name=";
    
    // Send the request to the webserver
    $response = _col_webservice_request( $common_name, $col_base . urlencode($common_name) );
    // Check for a valid response
    if( $response != "" ) {
        $response_data = unserialize( $response );
        
        // Check if we received something senseful
        if( $response_data === false ) {
            return;
        }
        
        // Get the results
        if( !isset( $response_data["results"] ) ) return false;
        $results = $response_data["results"];
        
        // Cycle through results
        foreach( $results as $result ) {
            // Check if we have a common name
            if( $result["name_status"] != "common name" ) continue;
            
            
        }
        
    }
    
    return false;
}

/**
 * Run a webservice request (using caching)
 * @param string $term Arbitrary string, used for caching
 * @param string $url web-service address
 * @return string Web-service response 
 */
function _col_webservice_request($term, $url) {
    $response = "";

    // Check for a cached result
    $cache_result = cache_get($term, 'cache_col');
    if ($cache_result != false) {
        $response = $cache_result->data;
    } else {
        $response = file_get_contents($url);

        // Cache the result
        cache_set($term, $response, 'cache_col', time() + 86400 );
    }

    return $response;
}
