<?php

/**
 * @file
 * Defines features and functions common to Piwik Reports
 */

/**
 * Implements hook_help().
 */
function piwik_reports_help($path, $arg) {
  global $user;

  switch ($path) {
    case (arg(0) == 'admin' && arg(1) == 'reports' && arg(2) == 'piwik_reports'):
      if ($user->uid && empty($user->data['piwik_reports_token_auth']) && (variable_get('piwik_reports_token_auth', '') == '')) {
        drupal_set_message(t('You need to configure your <em>Piwik authentication string</em> on the <a href="@user-edit">My account</a> page.', array('@user-edit' => url('user/' . $user->uid . '/edit'))), 'warning', FALSE);
      }
  }
}

/**
 * Implements hook_permission().
 */
function piwik_reports_permission() {
  return array(
    'access piwik reports' => array(
      'title' => t('Piwik reports access'),
      'description' => t('Allow access to Piwik reports.'),
    ),
    'administer piwik reports' => array(
      'title' => t('Administer Piwik reports'),
      'description' => t('Perform basic configuration tasks for Piwik reports.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function piwik_reports_menu() {
  // Reports
  $items['admin/reports/piwik_reports'] = array(
    'title' => 'Piwik web analytics',
    'page callback' => 'piwik_reports_menu_block_page',
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'description' => 'Reports on your website visitors, your popular pages, the search engines keywords they used... and so much more.',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/visitors'] = array(
    'title' => 'Visitors',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'visitors_overview'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/visitors/overview'] = array(
    'title' => 'Overview',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'visitors_overview'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/visitors/settings'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'visitors_settings'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/visitors/times'] = array(
    'title' => 'Times',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'visitors_times'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/visitors/locations'] = array(
    'title' => 'Locations provider',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'visitors_locations'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 4,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/actions'] = array(
    'title' => 'Actions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'actions_pageurls'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/actions/pages'] = array(
    'title' => 'Pages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'actions_pageurls'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/actions/outlinks'] = array(
    'title' => 'Outlinks',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'actions_outlinks'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/actions/downloads'] = array(
    'title' => 'Downloads',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'actions_downloads'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/referers'] = array(
    'title' => 'Referers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'referers_evolution'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/reports/piwik_reports/referers/evolution'] = array(
    'title' => 'Evolution',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'referers_evolution'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/referers/search'] = array(
    'title' => 'Search engines & keywords',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'referers_search'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/referers/websites'] = array(
    'title' => 'Websites',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'referers_websites'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/reports/piwik_reports/referers/websites'] = array(
    'title' => 'Websites',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('piwik_reports_reports', 'referers_websites'),
    'access arguments' => array('access piwik reports'),
    'file' => 'piwik_reports.pages.inc',
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  // if piwik is installed group with it, otherwise not
  if (module_exists('piwik')) {
    $items['admin/config/system/piwik/tracking'] = array(
      'title' => 'Tracking',
      'type' => MENU_NORMAL_ITEM,
      'description' => 'Configure the settings used to generate your Piwik tracking code.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer piwik'),
      'page arguments' => array('piwik_admin_settings_form'),
      'file path' => drupal_get_path('module', 'piwik'),
      'file' => 'piwik.admin.inc',
    );
    $items['admin/config/system/piwik/reports'] = array(
      'title' => 'Reports',
      'description' => 'Configure the settings for your Piwik reports.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('piwik_reports_admin_settings_form'),
      'access arguments' => array('administer piwik reports'),
      'type' => MENU_NORMAL_ITEM,
      'weight' => 10,
    );
  }
  else {
    $items['admin/config/system/piwik_reports'] = array(
      'title' => 'Piwik reports',
      'description' => 'Configure the settings for your Piwik reports.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('piwik_reports_admin_settings_form'),
      'access arguments' => array('administer piwik reports'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'piwik.admin.inc',
    );
  }
  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function piwik_reports_menu_alter(&$items) {
  if (module_exists('piwik')) {
    $items['admin/config/system/piwik'] = array(
      'title' => 'Piwik',
      'description' => 'Configure the settings for Piwik.',
      'access arguments' => array(array('administer piwik', 'administer piwik reports')),
      'access callback' => 'piwik_reports_any_access',
      'type' => MENU_NORMAL_ITEM,
    );
  }
}

/**
 * Implements hook_theme().
 */
function piwik_reports_theme() {
  return array(
    'piwik_reports' => array(
      'template' => 'piwik-reports',
      'variables' => array(
        'data_url' => NULL,
        'period' => NULL,
      ),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function piwik_reports_form_alter(&$form, $form_state, $form_id) {
  // Extend the form in "user/{userid}/edit/account".
  if ($form_id == 'user_profile_form' && $form['#user_category'] == 'account' && user_access('access piwik reports') && (variable_get('piwik_reports_token_auth', '') == '')) {
  global $user;
  $form['piwik_reports'] = array(
    '#type' => 'fieldset',
    '#title' => t('Piwik reports configuration'),
    '#weight' => 3,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['piwik_reports']['piwik_reports_token_auth'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik authentication string'),
    '#default_value' => (!empty($user->data['piwik_reports_token_auth'])) ? $user->data['piwik_reports_token_auth'] : 'anonymous',
    '#size' => 40,
    '#maxlength' => 40,
    '#description' => t('Click the <strong>Settings</strong> link in your Piwik account, then the <strong>Users</strong> tab and copy and paste your personal <strong>token_auth</strong> value into this field. If anonymous users have view permissions in Piwik you can set this value to <strong>anonymous</strong>. Or just ask the Piwik server administrator.'),
  );
  }
  elseif ($form_id == 'piwik_admin_settings_form') {
    drupal_set_title(t('Piwik tracking'));
  }
}

/**
 * Return true if use has any of the permissions
 *
 * @param $arguments
 *   array of permissions.
 *
 * @return
 */
function piwik_reports_any_access($arguments) {
  foreach ($arguments as $perm)
  if (user_access($perm)) return TRUE;
}

/**
 * Implements hook_user_presave().
 */
function piwik_reports_user_presave(&$edit, $account, $category) {

  if (isset($edit['piwik_reports_token_auth'])) {
    $edit['data']['piwik_reports_token_auth'] = $edit['piwik_reports_token_auth'];
  }
}

/**
 * Return the $form that handles piwik reports config page
 *
 * @param $form_state
 *   see form api.
 *
 * @return $form
 */
function piwik_reports_admin_settings_form($form_state) {
  drupal_set_title(t('Piwik reports'));
  $piwik_installed = module_exists('piwik');
  $form['piwik_reports_server'] = array(
    '#type' => 'fieldset',
    '#title' => t('Piwik report server'),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => $piwik_installed,
  );
  if ($piwik_installed) {
    $form['piwik_reports_server']['#description'] = t('Leave blank to use the same URL set in Piwik tracking.');
  }
  $form['piwik_reports_server']['piwik_reports_url_http'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik HTTP URL'),
    '#default_value' => variable_get('piwik_reports_url_http', ''),
    '#size' => 80,
    '#maxlength' => 255,
    '#required' => !$piwik_installed,
    '#weight' => 1,
    '#description' => t('The URL to your Piwik base directory. Example: "http://www.example.com/piwik/".'),
  );
  $form['piwik_reports'] = array(
    '#type' => 'fieldset',
    '#title' => t('Token auth'),
    '#weight' => 5,
    '#description' => t('To see piwik reports in Drupal you need a <strong>token_auth</strong> value. You can find it in the  <strong>Users</strong> tab under the <strong>Settings</strong> link in your Piwik account. Or just ask your Piwik server administrator.'),
  );
  $form['piwik_reports']['piwik_reports_token_auth'] = array(
    '#type' => 'textfield',
    '#title' => t('Piwik authentication string'),
    '#default_value' => variable_get('piwik_reports_token_auth', ''),
    '#size' => 40,
    '#maxlength' => 40,
    '#description' => t('Leave blank if you prefer each user setting his own, or paste it here to have a global <strong>token_auth</strong>. If anonymous users have view permissions in Piwik you can set this value to <strong>anonymous</strong>. Users still need "Access Piwik reports" permission to see the reports in Drupal.'),
  );
  $form['piwik_reports_sites'] = array(
    '#type' => 'fieldset',
    '#title' => t('Allowed sites'),
    '#weight' => 10,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#description' => t('List sites you want restrict your users access to.'),
  );
  if (variable_get('piwik_reports_token_auth', '') != '') {
    $sites = piwik_reports_get_sites(variable_get('piwik_reports_token_auth', ''));
    if (is_array($sites) && count($sites)) {
      $form['piwik_reports_sites']['piwik_reports_allowed_sites'] = array(
        '#type' => 'textfield',
        '#weight' => 10,
        '#collapsible' => TRUE,
        '#default_value' => variable_get('piwik_reports_allowed_sites', ''),
        '#collapsed' => TRUE,
        '#description' => t('List accessible sites id separated by a comma. Example: "1,4,12". Leave blank to let users see all sites accessible on piwik server with current token auth. Sites statistics that can be accessed with current token_auth are:'),
      );
      foreach ($sites as $site) {
        $form['piwik_reports_sites']['piwik_reports_allowed_sites']['#description'] .= '<br />' . (int) $site['idsite'] . ' - ' . check_plain($site['name']);
      }
    }
    else {
      $form['piwik_reports_sites']['piwik_reports_allowed_sites']['#markup'] = t('No accessible sites are present. Please check your token auth is correct and that it has view permission on Piwik server.');
    }
  }
  else {
    $form['piwik_reports_sites']['piwik_reports_allowed_sites']['#markup'] = t('Limits can be set only if a global token_auth is set.');
  }
  return system_settings_form($form);
}

/**
 * Return a list of sites which statistic are accessible on piwik server.
 *
 * @param $token_auth
 *   Piwik server token auth.
 *
 * @return $sites
 */
function piwik_reports_get_sites($token_auth) {
  // TODO: shall I cache this?
  $result = drupal_http_request(piwik_reports_get_url() . 'index.php?module=API&method=SitesManager.getSitesWithAtLeastViewAccess&format=JSON&token_auth=' . $token_auth);
  $sites = drupal_json_decode($result->data);
  return $sites;
}

/**
 * Return Piwik server url.
 *
 * @return $url
 */
function piwik_reports_get_url() {
  $url = variable_get('piwik_reports_url_http', '');
  if ($url == '') {
    if (module_exists('piwik')) {
      $url = variable_get('piwik_url_http', '');
    }
  }
  return $url;
}

